name: 不具合 (Bug)
description: 既存機能の不具合報告
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: environment
    attributes:
      label: 発生環境
      options:
        - local
        - dev
        - prod
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 再現手順
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: 完了条件
      value: |
        - [ ]
    validations:
      required: true
  - type: textarea
    id: refs
    attributes:
      label: 関連文書 / 関連PR / ログ
    validations:
      required: false
